### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by The-Chris-Davies** [The-Chris-Davies/EFSAE_pedal_controller#1]
- [ ] Select ready-on sound

- [ ] Implement APPS sensing
- [ ] Add Watchdog timer
- [ ] Integrate CAN BUS modules (use builtin CAN controller with interface circuit, or SPI CAN adapter)
- [ ] Add startup condition to catch bad reset / watchdog (system state flag + must read acc value
